### PR TITLE
Added an example for using PostgreSQL as a database registry for Feast

### PR DESCRIPTION
**Pull request by redhatHameed**
Added an example for using PostgreSQL as a database registry for Feast

### CODE REVIEW

**Comment by redhatHameed** [comment]
@etirelli added this example to support SQL based registry

**Review by jeremyary — COMMENTED** [review]
LGTM, thanks! Will leave to see if others want to review, then let it merge up later today. I couldn't find where materialize.png was referenced, so that may be extra but wanted to mention in case you had something in mind for it.

**Comment by redhatHameed** [comment]
> LGTM, thanks! Will leave to see if others want to review, then let it merge up later today. I couldn't find where materialize.png was referenced, so that may be extra but wanted to mention in case you had something in mind for it.
Thanks for review. 
Removed as this was extra added.

**Comment by redhatHameed** [comment]
> quick FYI - I'm disabling our plan/apply GH actions for now. They serve as good examples, but I don't think we have reason to live-sync our feature repo(s). LMK if you'd disagree, thanks!

Totally agree as like this example we are not using AWS or other cloud provider. For the time good to remove.

**Pull request merged**
